syntax = "proto3";

package velony.email.api.v1;

import "google/api/annotations.proto";
import "google/api/field_behavior.proto";

option go_package = "github.com/velonyapp/email/gen/api/v1;apiv1";

service EmailService {
  rpc SendEmail(SendEmailRequest) returns (SendEmailResponse) {
    option (google.api.http) = {
      post: "/v1:sendEmail"
      body: "*"
    };
  }
}

message EmailAddress {
  string address = 1 [
    (google.api.field_behavior) = REQUIRED
  ];
  optional string name = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message Email {
  EmailAddress from = 1 [
    (google.api.field_behavior) = REQUIRED
  ];
  repeated EmailAddress to = 2 [
    (google.api.field_behavior) = REQUIRED
  ];
  repeated EmailAddress cc = 3 [
    (google.api.field_behavior) = OPTIONAL
  ];
  repeated EmailAddress bcc = 4 [
    (google.api.field_behavior) = OPTIONAL
  ];

  string subject = 5 [
    (google.api.field_behavior) = REQUIRED
  ];
  optional string text = 6 [
    (google.api.field_behavior) = OPTIONAL
  ];
  optional string html = 7 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message SendEmailRequest {
  Email email = 1 [
    (google.api.field_behavior) = REQUIRED
  ];

  optional string idempotency_key = 2 [
    (google.api.field_behavior) = OPTIONAL
  ];
}

message SendEmailResponse {
  string message_id = 1;
}