// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/velonyapp/email/internal/application/command"
	"github.com/velonyapp/email/internal/application/query"
	"github.com/velonyapp/email/internal/conf"
	"github.com/velonyapp/email/internal/domain/service"
	"github.com/velonyapp/email/internal/infrastructure/data/mysql"
	"github.com/velonyapp/email/internal/infrastructure/email/resend"
	"github.com/velonyapp/email/internal/presentation/api"
	"github.com/velonyapp/email/internal/presentation/middleware"
	"github.com/velonyapp/email/internal/presentation/transport"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(email *conf.Email, data *conf.Data, confTransport *conf.Transport, logger *slog.Logger) (*kratos.App, func(), error) {
	db, err := mysql.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	template := mysql.NewTemplateRepo(db)
	templateIDPolicy := service.NewTemplateIDPolicy(template)
	unitOfWork := mysql.NewUnitOfWork(db)
	createTemplateHandler := command.NewCreateTemplateHandler(template, templateIDPolicy, unitOfWork)
	updateTemplateHandler := command.NewUpdateTemplateHandler(template, unitOfWork)
	deleteTemplateHandler := command.NewDeleteTemplateHandler(template, unitOfWork)
	client := resend.NewClient(email)
	emailSender := resend.NewSender(client)
	sendEmailHandler := command.NewSendEmailHandler(emailSender)
	sendEmailFromTemplateHandler := command.NewSendEmailFromTemplateHandler(template, emailSender)
	bus := command.NewBus(createTemplateHandler, updateTemplateHandler, deleteTemplateHandler, sendEmailHandler, sendEmailFromTemplateHandler)
	getTemplateHandler := query.NewGetTemplateHandler(template)
	listTemplatesHandler := query.NewListTemplatesHandler(template)
	queryBus := query.NewBus(getTemplateHandler, listTemplatesHandler)
	apiService := api.NewService(bus, queryBus)
	tracing := middleware.NewTracing()
	metrics, err := middleware.NewMetrics()
	if err != nil {
		return nil, nil, err
	}
	errorMapper := middleware.NewErrorMapper()
	validation := middleware.NewValidation()
	server := transport.NewGRPCServer(confTransport, apiService, tracing, metrics, errorMapper, validation)
	httpServer := transport.NewHTTPServer(confTransport, apiService, tracing, metrics, errorMapper, validation)
	rabbitMQConsumer := transport.NewRabbitMQConsumer(confTransport, bus)
	app := newApp(logger, server, httpServer, rabbitMQConsumer)
	return app, func() {
	}, nil
}
