// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v3"
	"github.com/velonyapp/email/internal/application/usecase"
	"github.com/velonyapp/email/internal/conf"
	"github.com/velonyapp/email/internal/info"
	"github.com/velonyapp/email/internal/infrastructure/email/resend"
	"github.com/velonyapp/email/internal/infrastructure/observability"
	"github.com/velonyapp/email/internal/infrastructure/transport"
	"github.com/velonyapp/email/internal/presentation/api"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(contextContext context.Context, service *info.Service, email *conf.Email, confTransport *conf.Transport, confObservability *conf.Observability, logger *slog.Logger) (*kratos.App, func(), error) {
	client := resend.NewClient(email)
	emailSender := resend.NewSender(email, client)
	sendEmailHandler := usecase.NewSendEmailHandler(emailSender)
	apiService := api.NewService(sendEmailHandler)
	tracesMiddleware := transport.NewTracesMiddleware()
	serverMetrics, err := observability.NewServerMetrics()
	if err != nil {
		return nil, nil, err
	}
	metricsMiddleware := transport.NewMetricsMiddleware(serverMetrics)
	validationMiddleware := transport.NewValidationMiddleware()
	server := transport.NewGRPCServer(confTransport, apiService, tracesMiddleware, metricsMiddleware, validationMiddleware)
	httpServer := transport.NewHTTPServer(confTransport, apiService, tracesMiddleware, metricsMiddleware, validationMiddleware)
	rabbitMQServer := transport.NewRabbitMQServer(confTransport, apiService)
	openTelemetry, cleanup, err := observability.NewOpenTelemetry(contextContext, confObservability, service)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, server, httpServer, rabbitMQServer, openTelemetry)
	return app, func() {
		cleanup()
	}, nil
}
